src/Entity/Images.php
<?php

namespace App\Entity;

use App\Repository\ImagesRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ImagesRepository::class)]
class Images
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 200, nullable: true)]
    private ?string $Name = null;

    #[ORM\ManyToOne(inversedBy: 'images')]
    private ?Produits $Products = null;

    public function getId(): ?int
    {
        return $this->id;
    }
    public function __toString()
    {
        return $this->Name;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(?string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getProducts(): ?Produits
    {
        return $this->Products;
    }

    public function setProducts(?Produits $Products): self
    {
        $this->Products = $Products;

        return $this;
    }
}

src/Entity/Produits.php
<?php

namespace App\Entity;

use App\Repository\ProduitsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;


#[ORM\Entity(repositoryClass: ProduitsRepository::class)]
class Produits
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 60)]
    private ?string $Name = null;

    #[ORM\Column]
    private ?int $reference = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $Description = null;

    #[ORM\Column]
    private ?bool $nouveaute = null;

    #[ORM\Column]
    private ?bool $Promotion = null;

    #[ORM\Column]
    private ?int $stock = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\Column(nullable: true)]
    private ?int $PoucentagePromotion = null;

    #[ORM\Column(nullable: true)]
    private ?float $PrixPromotion = null;

    #[ORM\Column(nullable: true)]
    private ?float $Avis = null;

    #[ORM\Column(length: 25, nullable: true)]
    private ?string $TailleRoueVTT = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $frein = null;

    #[ORM\Column(length: 30, nullable: true)]
    private ?string $pratiques = null;

    #[ORM\Column(length: 30, nullable: true)]
    private ?string $diametreDeRoue = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $cadre = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $amortisseur = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $fourche = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $derailleurAr = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $manettes = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pneus = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $cassette = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pedalier = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $potence = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $cintre = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $tigeDeSelle = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Selle = null;

    #[ORM\Column(nullable: true)]
    private ?float $Poids = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_At = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_At = null;

    #[ORM\ManyToOne(inversedBy: 'Products')]
    private ?Motorisation $motorisation = null;

    #[ORM\OneToMany(mappedBy: 'Products', targetEntity: Images::class, orphanRemoval: true,  cascade: ['persist', 'remove'])]
    private Collection $images;

    #[ORM\Column(length: 60, nullable: true)]
    private ?string $utilisation = null;

    #[ORM\ManyToMany(targetEntity: Category::class, mappedBy: 'products')]
    private Collection $categories;

    #[ORM\ManyToMany(targetEntity: Marque::class, mappedBy: 'products', cascade: ['persist'])]
    private Collection $marques;

    #[ORM\ManyToMany(targetEntity: Genre::class, mappedBy: 'products')]
    private Collection $genres;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $engine = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $battery = null;

    #[ORM\Column]
    private ?bool $isVae = null;

    public function __construct()
    {
        $this->updated_At = new \DateTimeImmutable();
        $this->created_At = new \DateTimeImmutable();
        $this->images = new ArrayCollection();
        $this->categories = new ArrayCollection();
        $this->marques = new ArrayCollection();
        $this->genres = new ArrayCollection();
    }
    public function __toString()
    {
        return $this->Name;
        return $this->genres;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getReference(): ?int
    {
        return $this->reference;
    }

    public function setReference(int $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function isNouveaute(): ?bool
    {
        return $this->nouveaute;
    }

    public function setNouveaute(bool $nouveaute): self
    {
        $this->nouveaute = $nouveaute;

        return $this;
    }

    public function isPromotion(): ?bool
    {
        return $this->Promotion;
    }

    public function setPromotion(bool $Promotion): self
    {
        $this->Promotion = $Promotion;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getPoucentagePromotion(): ?int
    {
        return $this->PoucentagePromotion;
    }

    public function setPoucentagePromotion(?int $PoucentagePromotion): self
    {
        $this->PoucentagePromotion = $PoucentagePromotion;

        return $this;
    }

    public function getPrixPromotion(): ?float
    {
        return $this->PrixPromotion;
    }

    public function setPrixPromotion(?float $PrixPromotion): self
    {
        $this->PrixPromotion = $PrixPromotion;

        return $this;
    }

    public function getAvis(): ?float
    {
        return $this->Avis;
    }

    public function setAvis(?float $Avis): self
    {
        $this->Avis = $Avis;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_At;
    }

    public function setCreatedAt(\DateTimeImmutable $created_At): self
    {
        $this->created_At = $created_At;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_At;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_At): self
    {
        $this->updated_At = $updated_At;

        return $this;
    }

    public function getMotorisation(): ?Motorisation
    {
        return $this->motorisation;
    }

    public function setMotorisation(?Motorisation $motorisation): self
    {
        $this->motorisation = $motorisation;

        return $this;
    }



    /**
     * @return Collection<int, Images>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setProducts($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getProducts() === $this) {
                $image->setProducts(null);
            }
        }

        return $this;
    }

    public function getUtilisation(): ?string
    {
        return $this->utilisation;
    }

    public function setUtilisation(?string $utilisation): self
    {
        $this->utilisation = $utilisation;

        return $this;
    }

    /**
     * @return Collection<int, Category>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories->add($category);
            $category->addProduct($this);
        }

        return $this;
    }


    public function removeCategory(Category $category): self
    {
        if ($this->categories->removeElement($category)) {
            $category->removeProduct($this);
        }

        return $this;
    }



    /**
     * @return Collection<int, Marque>
     */
    public function getMarques(): Collection
    {
        return $this->marques;
    }

    public function addMarque(Marque $marque): self
    {
        if (!$this->marques->contains($marque)) {
            $this->marques->add($marque);
            $marque->addProduct($this);
        }

        return $this;
    }

    public function removeMarque(Marque $marque): self
    {
        if ($this->marques->removeElement($marque)) {
            $marque->removeProduct($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Genre>
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres->add($genre);
            $genre->addProduct($this);
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        if ($this->genres->removeElement($genre)) {
            $genre->removeProduct($this);
        }

        return $this;
    }

    public function getTailleRoueVTT(): ?string
    {
        return $this->TailleRoueVTT;
    }

    public function setTailleRoueVTT(?string $TailleRoueVTT): self
    {
        $this->TailleRoueVTT  = $TailleRoueVTT;

        return $this;
    }

    public function getFrein(): ?string
    {

templates/components/_cardsSm.htm.twig
{# Composent Card SM #}


<a href="{{path('product_details', {id: productd.id} ) }} " class="relative bg-white mx-auto shadow-xl w-52  h-auto shadow-black rounded-r-3xl rounded-b-3xl md:hover:shadow-2xl md:hover:shadow-black md:hover:transition md:ease-in-out md:hover:-translate-y-2 md:hover:scale-110"></a>

templates/components/_cardsVtt.html.twig
<!-- Composent Card -->
<a href="{{path('product_details', {id: productd.id} ) }} " class="relative  bg-white mx-auto w-full shadow-xl  h-auto shadow-black rounded-r-3xl rounded-b-3xl md:w-52  md:hover:shadow-2xl md:hover:shadow-black md:hover:transition md:ease-in-out md:hover:-translate-y-2 md:hover:scale-110">
	<div class="w-24 absolute bottom-133">
		{% if productd.Promotion %}
			<p class="h-auto pl-2 text-sm text-white   w-auto bg-stone-950  rounded-e-3xl ">
				Promotion
			</p>
			<p class="h-auto mt-1 pl-2 text-sm w-12 bg-red-600 rounded-e-3xl">
				{{ productd.PoucentagePromotion}}
				%
			</p>
		{% endif %}
	</div>
	<div class=" h-auto rounded-r-3xl rounded-b-3xl p-2 flex md:flex-col items-center   mx-auto">
		<img src="{{ asset('assets/uploads/products/' ~ productd.images[0].name ) }}" class="rounded-tr-2xl w-32 h-28 md:w-48 md:h-40  object-cover  " alt="images VTT cube"/>
		<div class="  w-auto  h-auto  flex flex-col justify-start ml-4">
			{% for brandName in productd.marques %}
				<h4 class="text-sm font-semibold text-blue-900">{{ brandName.name }}</h4>
			{% endfor %}
			<h3 class="text-xs font-medium">{{ productd.name | u.truncate(40,'....')}}</h3>
			<p class=" text-xs mt-1  ">Cat:
				{% for catego in productd.categories %}
					<span class="text-green-600">
						{{ catego.name}}</span>
				{% endfor %}
			</p>
			<p class="hidden sm:block mt-1 text-xs font-thin text-gray-900">
				{{productd.description | u.truncate(60)}}
			</p>
			<p class="mt-2 text-xs">
				Prix:
				{% if productd.Promotion %}
					<span class="line-through text-gray-400 mr-3">
						{{productd.prix}}€
					</span>
					<span class="text-red-600">
						{{ productd.PrixPromotion}}€
					</span>
				{% else %}
					<span class=" text-blue-900 mr-3">
						{{productd.prix}}€
					</span>
				{% endif %}
			</p>
		</div>
	</div>
</a>

templates/components/_dropdownFilter.html.twig
<ul class="transition  duration-700 -translate-x-[30rem] lg:translate-x-0 w-2/4  z-30 h-full shadow-xl shadow-black fixed  left-0 lg:rounded-3xl lg:sticky backdrop-blur-3xl bg-black/20  top-28 lg:flex lg:flex-col lg:w-1/6 self-start px-4 text-sm font-medium text-white lg:mt-12 lg:mb-6 lg:ml-2" id="filtre">
	{{ form_start(form)}}
	<li class="rounded-2xl flex items-center justify-between my-1 mt-4 px-2 py-1 cursor-pointer hover:text-stone-950" id="dropdownCatergories">
		<h5 class="" id="colorsFiltersCategories">Catégories</h5>
		<span class="duration-200 hover:text-stone-500" id="arrowCategories">
			<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke-width="3" stroke="currentColor" class="w-6 h-6 text-pink-700">
				<path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5"/>
			</svg>
		</span>
	</li>
	<div class="text-left text-sm font-thin hidden" id="submenuFiltre">
		{{ form_row(form.categories) }}
	</div>
	<li class="rounded-2xl flex items-center justify-between my-1 px-2 py-1 cursor-pointer hover:text-stone-950" id="dropdownMarques">
		<h5 class="" id="colorsFiltersMarques">Marques</h5>
		<span class="duration-200 hover:text-stone-400" id="arrowMarques">
			<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke-width="3" stroke="currentColor" class="w-6 h-6 text-pink-700">
				<path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5"/>
			</svg>
		</span>
	</li>
	<div class="text-left text-sm font-thin hidden" id="submenuFiltreMarque">
		{{form_row(form.marques )}}
	</div>
	<li class="rounded-2xl flex items-center justify-between my-1 px-2 py-1 cursor-pointer hover:text-stone-950" id="dropdownGenre">
		<h5 class="" id="colorsFiltersGenre">Genre</h5>
		<span class="duration-200 hover:text-stone-400" id="arrowGenre">
			<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke-width="3" stroke="currentColor" class="w-6 h-6 text-pink-700">
				<path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5"/>
			</svg>
		</span>
	</li>
	<div class="text-left text-sm font-thin hidden" id="submenuFiltreGenre">
		{{form_row(form.genres)}}
	</div>
	{# <li class="rounded-2xl flex items-center justify-between my-1 px-2 py-1 cursor-pointer hover:text-stone-950" id="dropdownCouleurs">
		<h5 class="" id="colorsFiltersCouleur">Couleurs</h5>
		<span class="duration-200 hover:text-stone-400" id="arrowCouleurs">
			<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke-width="3" stroke="currentColor" class="w-6 h-6 text-pink-700">
				<path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5"/>
			</svg>
		</span>
	</li> #}
	{# <div class="text-left text-sm font-thin hidden" id="submenuFiltreCouleurs">
		<div class="flex flex-wrap my-2">
			<div class="w-6 h-6 rounded-full bg-gradient-to-tl from-black via-gray-800 to-black cursor-pointer hover:scale-110"></div>
			<div class="w-6 h-6 rounded-full bg-gradient-to-tl from-blue-900 via-blue-500 to-blue-900 cursor-pointer ml-2 hover:scale-110"></div>
			<div class="w-6 h-6 rounded-full bg-gradient-to-tl from-yellow-900 via-yellow-500 to-yellow-900 cursor-pointer ml-2 hover:scale-110"></div>
			<div class="w-6 h-6 rounded-full bg-gradient-to-tl from-green-900 via-green-400 to-green-900 cursor-pointer ml-2 hover:scale-110"></div>
			<div class="w-6 h-6 rounded-full bg-gradient-to-tl from-red-900 via-red-500 to-red-900 cursor-pointer ml-2 hover:scale-110"></div>
		</div>
	</div> #}
	<button type'submit' class="mx-auto my-2 flex items-center justify-between  cursor-pointer">
		<div class="group buttonFilter  ">
			<span class="spanFilter ">
				Valider
			</span>
		</div>

	</button>
	{{ form_end(form)}}
</ul>

templates/components/_fileAriane.html.twig
<div class="mx-auto sticky top-20  px-6 block backdrop-blur-3xl shadow-2xl bg-black/20 z-40">
	<div class="max-w-10xl delay-150 sticky top-20 h-8 bg-none text-slate-900 flex items-center justify-start">
		 <div class="cursor-pointer transition duration-700 translate-x-[0rem] mr-4 lg:hidden" id="filtreMobile">
			<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke-width="3" stroke="currentColor" class="w-6 h-6 text-pink-600">
				<path stroke-linecap="round" stroke-linejoin="round" d="M11.25 4.5l7.5 7.5-7.5 7.5m-6-15l7.5 7.5-7.5 7.5"/>
			</svg>
		</div>
	</div>
</div>

templates/components/_pagination.html.twig
{#{% if pageCount >1 %}

	<div aria-label="Page navigation example" class="">
		<ul class="inline-flex -space-x-px text-sm">
			{% if first is defined and current != first %}
				<li>
					<a href="{{ path(route, (query|merge({(pageParameterName): current -1 }))) }}" class="flex items-center justify-center px-3 h-8 ml-0 leading-tight text-gray-500 bg-white border border-gray-300 rounded-l-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">Previous</a>
				</li>
			{% endif %}
			{% for page in pagesInRange %}
				{% if page != current %}
					<li>
						<a href="{{ path(route, query|merge({(pageParameterName): page})) }}" class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
							{{ page }}
						</a>
					</li>
				{% else %}
					<li>
						<a href="{{ path(route, query|merge({(pageParameterName): page})) }}" class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
							{{ page }}
						</a>
					</li>
				{% endif %}
			{% endfor %}
			{% if last is defined and current != last %}
				<a href="{{ path(route, (query|merge({(pageParameterName): current +1 }))) }}" class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 rounded-r-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">Next</a>
			{% endif %}
		</li>
	</ul>
</div>{% endif %}
#}

{% if pageCount > 1 %}
	<div class="flex items-center  rounded-3xl">
		{% if first is defined and current != first %}
			<a class="relative block p-2 mr-1   bg-transparent outline-none rounded-full text-stone-200  " href="{{ path(route, (query|merge({(pageParameterName): current -1 }))) }}" tabindex="-1" aria-disabled="true">
				&lsaquo;
			</a>
		{% endif %}
		{% for page in pagesInRange %}
			{% if page != current %}
				<a class="page-link relative block p-2 border-0 bg-transparent outline-none transition-all duration-300 rounded-full text-stone-950 hover:text-stone-950 hover:bg-stone-400 focus:shadow-none" href="{{ path(route, query|merge({(pageParameterName): page})) }}">
					{{ page }}
				</a>
			{% else %}
				<a href="{{ path(route, query|merge({(pageParameterName): page})) }}" class=" relative block p-2 mx-1 border-0 bg-pink-900 outline-none transition-all duration-300 rounded-full text-white hover:text-white hover:bg-pink-800 shadow-md focus:shadow-md">
					{{ page }}
				</a>
			{% endif %}
		{% endfor %}
		{% if last is defined and current != last %}
			<a class="relative block p-2 ml-1 bg-transparent outline-none rounded-full text-stone-200 " href="{{ path(route, (query|merge({(pageParameterName): current +1 }))) }}" tabindex="-1" aria-disabled="true">
				&rsaquo;
			</a>
		{% endif %}
	</div>
{% endif %}

templates/components/_search.html.twig
<form class="flex items-center" action="{{ path('search') }}">
	<label for="simple-search" class="sr-only">Search</label>
	<div class="relative w-full">
		<div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
			<svg aria-hidden="true" class="w-5 h-5 text-s_Xligth dark:text-gray-400" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
				<path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path>
			</svg>
		</div>
		<input type="text" id="simple-search" name="q" type="search" aria-label="Search" class=" pl-10 h-8 bg-p_darck border border-p_ligth text-withe text-sm rounded-lg focus:ring-s_Xligth focus:border-s_Xligth block w-full p-2.5 " placeholder="Recherche" required>
	</div>

	<button type="submit" class=" h-8 w-8 p-1 ml-2 text-sm font-medium text-white bg-p_darck rounded-lg border border-stone-600 hover:bg-p_ligth hover:text-s_Xligth focus:ring-2 focus:outline-none focus:ring-s_Xligth ">
		<svg class="w-5 h-5" fill="none" stroke="currentColor" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
			<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
		</svg>
		<span class="sr-only">Search</span>
	</button>
</form>